server:
  port: 8083

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jorgevelasquezv/microservices-springboot.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: admin
      password: admin
      roles: manager
